### ISSUE TITLE
eclipse oxygen.2 +gluon plugin 2.5.1 still not working?

### ISSUE THREAD

**Issue by kaonick** [gluonhq/ide-plugins#8] opened 2018-02-05 04:05 UTC
install buildship 2.0
install gluon plugin 2.5
create gluon project than the wizard always stop in finish.
can not push finish.
stackoverflow say to http://gluonhq.com/upgrading-open-sourcing-gluon-plugin-eclipse/
but still not working.
Can you help me that.

**Comment by tiainen** [comment] 2018-02-06 10:27
Duplicate of #6

**Closed** 2018-02-06 10:27 UTC
Labels: eclipse
